### ISSUE TITLE
gitm clone doesn't work

### ISSUE THREAD

**Issue by Yehonal** [snowdream/gitm#5]
i've this error:

`sudo gitm clone https://raw.githubusercontent.com/snowdream/gitm/master/examples/repository/repo.gitm
child_process.js:1163
    throw errnoException(err, 'spawn');
          ^
Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1163:11)
    at exports.spawn (child_process.js:996:9)
    at Command.executeSubCommand (/usr/local/lib/node_modules/gitm/node_modules/commander/index.js:534:14)
    at Command.parse (/usr/local/lib/node_modules/gitm/node_modules/commander/index.js:463:17)
    at gitm_main (/usr/local/lib/node_modules/gitm/bin/gitm:53:14)
    at main (/usr/local/lib/node_modules/gitm/bin/gitm:26:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/gitm/bin/gitm:12:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
`

Permissions on folder are 777

**Comment by snowdream** [comment]
The system of your PC is Mac?

**Comment by snowdream** [comment]
The system of your PC is Mac?

**Comment by snowdream** [comment]
The system of your PC is Mac?

**Comment by snowdream** [comment]
The system of your PC is Mac?

**Comment by snowdream** [comment]
The system of your PC is Mac?

**Comment by snowdream** [comment]
The system of your PC is Mac?

**Comment by snowdream** [comment]
The system of your PC is Mac?

**Comment by snowdream** [comment]
The system of your PC is Mac?

**Comment by snowdream** [comment]
The system of your PC is Mac?

**Comment by snowdream** [comment]
The system of your PC is Mac?

**Comment by snowdream** [comment]
The system of your PC is Mac?

**Comment by Yehonal** [comment]
linux

**Comment by Yehonal** [comment]
PS could you accept my hangout request?

**Comment by snowdream** [comment]
I test the gitm with Windows 7.

**Comment by snowdream** [comment]
@Yehonal  I have accepted your hangout request.

**Comment by snowdream** [comment]
Fixed
